### 1. user 등록
POST {{root-url}}/api/user/sign-up
Content-Type: application/json

{
  "email": "yhj7124@naver.com",
  "password": "test1234",
  "name": "abc",
  "phone": "01099157124",
  "apartmentCode": "A12345678",
  "building": 101,
  "unit": 101
}

### 2. user 로그인
POST {{root-url}}/api/user/login
Content-Type: application/json

{
  "email": "abc@gmail.com",
  "password": "test1234"
}

### 3. user 정보
GET {{root-url}}/api/user/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhYmNAZ21haWwuY29tIiwicm9sZXMiOlsiTUVNQkVSIl0sImlhdCI6MTY5NDI2OTU1NiwiZXhwIjoxNjk0MzU1OTU2fQ.h1QWdofPihFjFfdKMn7S8d-ZTy_N2WRWD8H7rSkNM9PKpwonChJPVutttu67qfqo32r1r4Oc47uGaFqK9AmDLA

### 4. user 목록
GET {{root-url}}/api/user/1,2,3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhYmNAZ21haWwuY29tIiwicm9sZXMiOlsiTUVNQkVSIl0sImlhdCI6MTY5NDI2OTU1NiwiZXhwIjoxNjk0MzU1OTU2fQ.h1QWdofPihFjFfdKMn7S8d-ZTy_N2WRWD8H7rSkNM9PKpwonChJPVutttu67qfqo32r1r4Oc47uGaFqK9AmDLA
