### 1-1. user 등록
POST {{gateway-url}}/api/user/sign-up
Content-Type: application/json

{
  "email": "yhj7124@naver.com",
  "password": "test1234",
  "name": "abc",
  "phone": "01012345678",
  "apartmentCode": "A12345678",
  "building": 101,
  "unit": 101
}

### 1-2. user 로그인
POST {{gateway-url}}/api/user/login
Content-Type: application/json

{
  "email": "yhj7124@naver.com",
  "password": "test1234"
}

### 1-3. user 정보
GET {{gateway-url}}/api/user/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ5aGo3MTI0QGdvb2dsZS5jb20iLCJyb2xlcyI6WyJVTlJFR0lTVEVSRUQiXSwiaWF0IjoxNjk3Mjk5MDc0LCJleHAiOjE2OTczODU0NzR9.ZrjL_KJTcHOr_45nT32aGNmhD8syjVroX29zQj39G9hKlcAykxzS348_UJRkPPxBRp-BtKSax3dbjPOI7XqxGg

### 1-4. user 목록
GET {{gateway-url}}/api/user/1,2,3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ5aGo3MTI0QGdvb2dsZS5jb20iLCJyb2xlcyI6WyJVTlJFR0lTVEVSRUQiXSwiaWF0IjoxNjk3Mjk5MDc0LCJleHAiOjE2OTczODU0NzR9.ZrjL_KJTcHOr_45nT32aGNmhD8syjVroX29zQj39G9hKlcAykxzS348_UJRkPPxBRp-BtKSax3dbjPOI7XqxGg


### 2-1. userRoleToken 생성
POST {{gateway-url}}/api/user/role/token
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ5aGo3MTI0QGdvb2dsZS5jb20iLCJyb2xlcyI6WyJVTlJFR0lTVEVSRUQiXSwiaWF0IjoxNjk3Mjk5MDc0LCJleHAiOjE2OTczODU0NzR9.ZrjL_KJTcHOr_45nT32aGNmhD8syjVroX29zQj39G9hKlcAykxzS348_UJRkPPxBRp-BtKSax3dbjPOI7XqxGg

{
  "apartmentCode": "A12345678",
  "userRole": "LEADER"
}

### 2-2. token 으로 user role 변경
POST {{gateway-url}}/api/user/role/change/f14f2fb4-e4e7-4b59-9735-0b483a
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ5aGo3MTI0QG5hdmVyLmNvbSIsInJvbGVzIjpbIlVOUkVHSVNURVJFRCJdLCJpYXQiOjE2OTcyOTkyNjksImV4cCI6MTY5NzM4NTY2OX0.q-r1ApvSskKG5xnNBJuY8PclOurno4u3qZnvjbswfzOItx8HTNNIu-SOuRRnYdrrJRZeCOxMndHWbuSI1nUQag
