### 1. user 등록
POST {{root-url}}/api/user/sign-up
Content-Type: application/json

{
  "email": "yhj7124@naver.com",
  "password": "test1234",
  "name": "abc",
  "phone": "01099157124",
  "apartmentCode": "A12345678",
  "building": 101,
  "unit": 101
}

### 2. user 로그인
POST {{root-url}}/api/user/login
Content-Type: application/json

{
  "email": "abc@gmail.com",
  "password": "test1234"
}

### 3. user 정보
GET {{root-url}}/api/user/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhYmNAZ21haWwuY29tIiwicm9sZXMiOlsiVU5SRUdJU1RFUkVEIl0sImlhdCI6MTY5MzY1ODU5NSwiZXhwIjoxNjkzNzQ0OTk1fQ.I0l1Lu2RLJrv9EbGIkKslj7mDPn7gAr6w85GXjpRyfkTZuGS3uuFBaNgSCfDKHbVx6Xmr82VYc-hIbIiZSJYFA
