### 1. 투표
POST {{root-url}}/api/vote/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhYmNAZ21haWwuY29tIiwicm9sZXMiOlsiTUVNQkVSIl0sImlhdCI6MTY5NDI2OTU1NiwiZXhwIjoxNjk0MzU1OTU2fQ.h1QWdofPihFjFfdKMn7S8d-ZTy_N2WRWD8H7rSkNM9PKpwonChJPVutttu67qfqo32r1r4Oc47uGaFqK9AmDLA

{
  "selectOptionId": 1
}

### 2. 가장 최근 투표 결과 조회
GET {{root-url}}/api/vote/agenda/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhYmNAZ21haWwuY29tIiwicm9sZXMiOlsiTUVNQkVSIl0sImlhdCI6MTY5NDI2OTU1NiwiZXhwIjoxNjk0MzU1OTU2fQ.h1QWdofPihFjFfdKMn7S8d-ZTy_N2WRWD8H7rSkNM9PKpwonChJPVutttu67qfqo32r1r4Oc47uGaFqK9AmDLA


### 3. 선택지 투표수 조회
GET {{root-url}}/api/vote/agenda/1/select-option/2/count
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhYmNAZ21haWwuY29tIiwicm9sZXMiOlsiTUVNQkVSIl0sImlhdCI6MTY5NDI2OTU1NiwiZXhwIjoxNjk0MzU1OTU2fQ.h1QWdofPihFjFfdKMn7S8d-ZTy_N2WRWD8H7rSkNM9PKpwonChJPVutttu67qfqo32r1r4Oc47uGaFqK9AmDLA

### 4. 선택지 정보 조회
GET {{root-url}}/api/vote/agenda/1/select-option/1/info
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhYmNAZ21haWwuY29tIiwicm9sZXMiOlsiTUVNQkVSIl0sImlhdCI6MTY5NDI2OTU1NiwiZXhwIjoxNjk0MzU1OTU2fQ.h1QWdofPihFjFfdKMn7S8d-ZTy_N2WRWD8H7rSkNM9PKpwonChJPVutttu67qfqo32r1r4Oc47uGaFqK9AmDLA
