server:
  port: 8081

spring:
  application:
    name: vote-service
  profiles:
    active: local
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/resident?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: zerobase
    pool:
      max-size: 100
      validation-query: SELECT 1

  kafka:
    bootstrap-servers: http://localhost:9092

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans
