server:
  port: 8086
  servlet:
    context-path: /batch

  ## Mysql Configs
spring:
  datasource:
    url: jdbc:mysql://my-sql:3306/resident?rewriteBatchedStatements=true
    username: root
    password: zerobase
    driver-class-name: com.mysql.cj.jdbc.Driver
    show-sql: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never
  kafka:
    bootstrap-servers: http://kafka:9092

batch:
  schedule:
    cron: 0 6 * * * *

