server:
  port: 8086
  servlet:
    context-path: /batch

  ## Mysql Configs
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resident
    username: root
    password: zerobase
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate: use-new-id-generator-mappings=false
