apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  selector:
    app: config
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
        - name: config
          image: tkdlqh2/residents-meeting-config:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: 'prod'