apiVersion: v1
kind: Service
metadata:
  name: schedule-consumer-service
spec:
  selector:
    app: schedule-consumer
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-consumer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schedule-consumer
  template:
    metadata:
      labels:
        app: schedule-consumer
    spec:
      containers:
        - name: schedule-consumer
          image: tkdlqh2/residents-meeting-schedule-consumer:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: 'prod'