apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: tkdlqh2/residents-meeting-user:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: 'prod'