create table users
(
    building       integer      not null,
    unit           integer      not null,
    created_time   timestamp(6),
    id             bigint generated by default as identity,
    updated_time   timestamp(6),
    apartment_code varchar(255),
    email          varchar(255) not null unique,
    name           varchar(255) not null,
    password       varchar(255) not null,
    phone          varchar(255) not null unique,
    role           varchar(255) not null,
    primary key (id)
);

create table agenda
(
    id             bigint generated by default as identity,
    apartment_code varchar(255) not null,
    title          varchar(255) not null,
    details        clob,
    end_date       date         not null,
    created_time   timestamp(6),
    updated_time   timestamp(6),
    primary key (id)
);

create table select_option
(
    id           bigint generated by default as identity,
    agenda_id    bigint       not null,
    summary      varchar(255) not null,
    details      clob,
    created_time timestamp(6),
    updated_time timestamp(6),
    primary key (id)
);

create table vote
(
    id               bigint generated by default as identity,
    user_id          bigint not null,
    select_option_id bigint not null,
    created_time     timestamp(6),
    updated_time     timestamp(6),
    primary key (id)
);

create table agenda_history
(
    end_date date         not null,
    id       bigint       not null,
    title    varchar(255) not null,
    details  clob,
    primary key (id)
);

create table agenda_history_select_options
(
    agenda_history_id bigint not null,
    select_options_id bigint not null unique
);


create table select_option_history
(
    id        bigint       not null,
    agenda_id bigint,
    details   varchar(255),
    summary   varchar(255) not null,
    count     integer      not null,
    primary key (id)
);

alter table if exists select_option
    add constraint fk_select_option_agenda foreign key (agenda_id) references agenda;
alter table if exists select_option_history
    add constraint fk_select_option_history_agenda_history foreign key (agenda_id) references agenda_history;
alter table if exists vote
    add constraint fk_vote_select_option foreign key (select_option_id) references select_option;
alter table if exists vote
    add constraint fk_vote_users foreign key (user_id) references users